#!/bin/bash
version=`cat ./capstone.version`
echo $version
wget -N "https://github.com/aquynh/capstone/archive/"$version".tar.gz" && tar -xvzf $version".tar.gz" -C ./
mv capstone-$version capstone
rm -f $version.tar.gz

version=`cat ./keystone.version`
echo $version
wget -N "https://github.com/keystone-engine/keystone/archive/"$version".tar.gz" && tar -xvzf $version".tar.gz" -C ./
mv keystone-$version keystone
rm -f $version.tar.gz
